# Constraints
MAX_DISPLAY_NAME_LENGTH = 50

MAX_TAG_NAME_LENGTH = 32
MAX_TAG_SLUG_LENGTH = 32
MAX_NAME_INGREDIENT_LENGTH = 128
MAX_MEASUREMENT_UNIT_NAME_LENGTH = 64
MAX_RECIPE_NAME_LENGTH = 256

MAX_LINK_LENGTH = 8

MIN_COOKING_TIME = 1
MIN_AMOUNT = 1
MAX_COOKING_TIME = 60 * 24
MAX_AMOUNT = 10000
