volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram-db
    env_file: .env
    image: postgres:13.10
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-backend
    env_file: .env
    image: rockur/foodgram_backend
    volumes:
      - static:/app/staticfiles/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    container_name: foodgram-frontend
    env_file: .env
    image: rockur/foodgram_frontend
    command: cp -r build result_build
    volumes:
      - ./frontend:/app/result_build/

  nginx:
    container_name: foodgram-nginx
    env_file: .env
    ports:
      - "7000:80"
    image: nginx:1.25.4-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/app/staticfiles/
      - media:/app/media/
    depends_on:
      - db
      - backend
